version: 0
metadata:
  name: "Positron"
  description: "continuous integration for Positron"
  owner: "{{ event.head.user.email }}"
  source: "{{ event.head.repo.url }}"
tasks:
  - provisionerId: "{{ taskcluster.docker.provisionerId }}"
    workerType: "{{ taskcluster.docker.workerType }}"
    extra:
      github:
        env: true
        events:
          - pull_request.opened
          - pull_request.synchronize
          - pull_request.reopened
          - push
    payload:
      env:
        GECKO_DEV_URL: https://github.com/mozilla/gecko-dev
        MOZCONFIG: ./positron/config/mozconfig
        SHELL: /bin/bash
      maxRunTime: 14400 # 60 * 60 * 4 seconds (i.e. four hours)
      image: "mykmelez/docker-build-positron:latest"
      command:
        - /bin/bash
        - -c
        - >
          git config --global gc.auto 0 &&
          tc-vcs checkout repo $GECKO_DEV_URL $GITHUB_HEAD_REPO_URL $GITHUB_HEAD_BRANCH &&
          cd repo/ &&
          git submodule update --init &&
          ./mach build
    metadata:
      name: "check_out_and_build_opt"
      description: "check out the repository and build optimized"
      owner: "{{ event.head.user.email }}"
      source: "{{ event.head.repo.url }}"
  - provisionerId: "{{ taskcluster.docker.provisionerId }}"
    workerType: "{{ taskcluster.docker.workerType }}"
    extra:
      github:
        env: true
        events:
          - pull_request.opened
          - pull_request.synchronize
          - pull_request.reopened
          - push
    payload:
      env:
        GECKO_DEV_URL: https://github.com/mozilla/gecko-dev
        MOZCONFIG: ./positron/config/mozconfig-debug
        SHELL: /bin/bash
      maxRunTime: 14400 # 60 * 60 * 4 seconds (i.e. four hours)
      image: "mykmelez/docker-build-positron:latest"
      command:
        - /bin/bash
        - -c
        - >
          git config --global gc.auto 0 &&
          tc-vcs checkout repo $GECKO_DEV_URL $GITHUB_HEAD_REPO_URL $GITHUB_HEAD_BRANCH &&
          cd repo/ &&
          git submodule update --init &&
          ./mach build
    metadata:
      name: "check_out_and_build_debug"
      description: "check out the repository and build debug"
      owner: "{{ event.head.user.email }}"
      source: "{{ event.head.repo.url }}"
