language: cpp
sudo: required
dist: trusty
compiler:
- clang
os:
- linux
- osx
cache:
  - ccache
  - apt
env:
  global:
    - MAKE_ARGS=-j4
    - USE_CCACHE=true
  matrix:
    - MACH_COMMAND="configure"
    - MACH_COMMAND="build export"
    - MACH_COMMAND="build compile"
    - MACH_COMMAND="build libs"
    - MACH_COMMAND="build tools"
    - MACH_COMMAND="build binaries"
    - MACH_COMMAND="build install-manifests"
    - MACH_COMMAND="build"
addons:
  apt:
    packages:
      - autoconf2.13
      - build-essential
      - ccache
      - python-dev
      - python-pip
      - python-setuptools
      - unzip
      - uuid
      - zip
      - libasound2-dev
      - libdbus-glib-1-dev
      - libgconf2-dev
      - libgtk2.0-dev
      - libgtk-3-dev
      - libpulse-dev
      - yasm
before_install:
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew update && brew install autoconf213 yasm ccache; fi
script:
  - ./mach $MACH_COMMAND
notifications:
  email: true
